###
GET http://localhost:5000/api/expenses
###
GET http://localhost:5000/api/expenses/id/1

###
GET http://localhost:5000/api/expenses/month/1

###
GET http://localhost:5000/api/expenses/shop/Niagara

###
POST http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
  "item": "Groceries",
  "shop": "Prisma",
  "category": "Necessities",
  "price": 123.98,
  "date": "2023-01-04"
}
###
POST http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
  "item": "PS5",
  "shop": "Verkkokauppa",
  "category": "Necessities",
  "price": 669.99,
  "date": "2023-01-01"
}

### PUT NOT WORKING: GIVEN INFORMATION IS NOT FORWARDED TO CREATEITEM
PUT http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
  "id": 1,
  "item": "Ice cream",
  "shop": "Citymarket",
  "category": "Leisure",
  "price": 4.95,
  "date": "2023-01-01"
}

### WORKING
DELETE http://localhost:5000/api/expenses/3